### ISSUE TITLE
How to reduce the time-consuming during training processes?

### ISSUE THREAD

**Issue by LiHui1116** [YicongHong/Recurrent-VLN-BERT#20]
Hi ,@YicongHong
Thank you so much for the great work you do. I reproduced Recurrent VLN BERT on the R2R and REVERIE datasets according to the file readme.md. During the training process, it takes about 2,500 minutes for a single GPU to run 200,000 iterations. Even if dual GPUs are used, this time still does not drop at all. I'm very confused about this. Do you also need such a long time in the training process? Why does adding GPUs not increase speed? What limits the improvement of speed in training process? Is there any other way to improve the speed besides reducing the number of iterations?

**Comment by YicongHong** [comment]
Hi @LiHui1116,
2,500 minutes on a single GPU of training time sounds very reasonable. Most of the other VLN agents take much longer, due to the long traveling horizon and slow interaction steps. 
However, using multiple GPUs should reduce training time significantly, but my original code does not support that, so please double check your implementation.
Reducing the number of iteration doesn't really improve the speed, because the model requires sufficient steps to converage.
Hope this helps, cheers.

**Comment by GengzeZhou** [comment]
Check it out: https://github.com/GengzeZhou/Recurrent-VLN
We support DDP and the latest version of Matterport3DSimulator here.
