### ISSUE TITLE
Failed to build Matterport3D Simulator

### ISSUE THREAD

**Issue by jasonppy** [YicongHong/Recurrent-VLN-BERT#6]
Hi Yicong,

This is not directly related to your code, but I've spent hours trying to follow the [Matterport3DSimulator repo](https://github.com/peteanderson80/Matterport3DSimulator) to build it, I encountered issues either building with or without Docker.

With docker, MatterSim can be built, but it is only available for system python, since I used anaconda on the lab server, importing matterSim will fail in my anaconda environment.

Without docker, the build failed. It's some line in the code has an error. line 59 of src/lib/NavGraph.cpp. CV_LOAD_IMAGE_ANYDEPTH is not defined in the scope. I only downloaded `matterport_skybox_images`, and this might be the problem (however, the readme.md in matterport3dsimulator says `matterport_skybox_images` is what you need to get the simulator to build and work) I wonder what data did you download from matterport 3D dataset?

Best,
Jason

**Comment by YicongHong** [comment]
Hi Jason,

About the installation problems, I didn't meet the issues you mentioned either with or withour docker, maybe you should look into the Matterport3DSimulator repo, or ask for help there.

About the data, if you don't want to visualize anything, you don't need to download any images. Otherwise, I believe `matterport_skybox_images` is all you need, and don't forget to set `sim.setDepthEnabled` as `sim.setDepthEnabled(False)` if you haven't download and preprocess the depth image.

Hope it helps. Cheers,
Yicong

**Comment by jasonppy** [comment]
Thanks for the reply! I solve the problem building with Docker!

**Comment by haomengz** [comment]
Hi @jasonppy, I am wondering how you were dealing with the problem. I have created a conda environment for the project and installed the Matterport3D using docker (inside the conda environment). If I want to run the test code in this repo, do I have to do that inside the docker as well?

**Comment by jasonppy** [comment]
sorry I don't remember that
